# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('personal_exp', models.IntegerField(blank=True, null=True)),
                ('sharing_exp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shyam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=50)),
                ('personal_exp', models.IntegerField(blank=True, null=True)),
                ('sharing_exp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
